---

# 3.3.4 Ensure permissions on /etc/hosts.allow are configured

- name: "3.3.4 -> Ensure permissions on /etc/hosts.allow are configured"
  file:
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  tags:
      - level1
      - scored
      - hosts
      - control_5.1
      - rule_3.3.4
      - section_3.3