---

# 1.5.2 -Ensure permissions on bootloader config are configured

- name: "1.5.2 -> Ensure permissions on bootloader config are configured"
  file:
      path: "/boot/grub/grub.cfg"
      owner: root
      group: root
      mode: "og-rwx"
  tags:
    - level1
    - scored
    - grub
    - control_5.1
    - rule_1.5.2
    - section_1.5