---

# EXTRAS - Install clamav

- name: "EXTRAS - Install clamav"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - clamav
      - clamav-daemon
  tags:
      - extras
      - clamav