---

# 5.4.1.1  Ensure password expiration is 365 days or less

- name: "5.4.1.1 ->  Ensure password expiration is 365 days or less"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: "^PASS_MAX_DAYS"
    line: "PASS_MAX_DAYS {{ pass_expire_in_days }}"
  tags:
      - level1
      - scored
      - control_4.4
      - rule_5.4.1.1
      - section_5.4