---

# 5.4.5 Ensure default user shell timeout is 900 seconds or less

- name: "5.4.5 -> Ensure default user shell timeout is 900 seconds or less"
  block:
    - name: "5.4.5 -> Ensure default user shell timeout is 900 seconds or less [1/3]"
      lineinfile:
        state: present
        dest: /etc/bash.bashrc
        create: true
        regexp: '^TMOUT='
        line: "TMOUT=600"

    - name: "5.4.5 -> Ensure default user shell timeout is 900 seconds or less [2/3]"
      lineinfile:
        state: present
        dest: /etc/profile
        create: true
        regexp: '^TMOUT='
        line: "TMOUT=600"

    - name: "5.4.5 -> Ensure default user shell timeout is 900 seconds or less [3/3]"
      lineinfile:
        state: present
        dest: /etc/profile.d/99-tmout.sh
        create: true
        regexp: '^TMOUT='
        line: "TMOUT=600"
  tags:
    - level1
    - control_16.11
    - rule_5.4.5
    - scored
    - section_5.4
  