---

# 5.4.1.3 Ensure password expiration warning days is 7 or more

- name: "5.4.1.3 -> Ensure password expiration warning days is 7 or more"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: "^PASS_WARN_AGE"
    line: "PASS_WARN_AGE {{ pass_warn_age }}"
  tags:
      - level1
      - scored
      - control_4.4
      - rule_5.4.1.3
      - section_5.4