---

# 5.2.20  Ensure SSH PAM is enabled 

- name: "5.2.20 -> Ensure SSH PAM is enabled"
  template:
      src: etc/ssh/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
  tags:
      - level1
      - scored
      - control_5.1
      - sshd
      - rule_5.2.20