---

# 5.2.17 Ensure SSH LoginGraceTime is set to one minute or less

- name: "5.2.17 -> Ensure SSH LoginGraceTime is set to one minute or less"
  template:
      src: etc/ssh/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
  tags:
      - level1
      - scored
      - control_5.1
      - sshd
      - rule_5.2.17
