---

# 5.2.2  Ensure permissions on SSH private host key files are configured

- name: "5.2.2 -> Ensure permissions on SSH private host key files are configured (1/2)"
  command: find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chown root:root {} \;
  tags:
      - level1
      - scored
      - control_14.6
      - sshd
      - rule_5.2.2
      - section_5.2

- name: "5.2.2 -> Ensure permissions on SSH private host key files are configured (2/2)"
  command: find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chmod 0600 {} \;
  tags:
      - level1
      - scored
      - control_14.6
      - sshd
      - rule_5.2.2
      - section_5.2