---

# 5.2.9  Ensure SSH HostbasedAuthentication is disabled

- name: "5.2.9 ->  Ensure SSH HostbasedAuthentication is disabled"
  template:
      src: etc/ssh/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
  tags:
      - level1
      - scored
      - control_16.13
      - sshd
      - rule_5.2.9
