---

# 5.2.19 Ensure SSH warning banner is configured

- name: "5.2.19 -> Ensure SSH warning banner is configured"
  template:
      src: etc/ssh/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
  tags:
      - level1
      - scored
      - control_5.1
      - sshd
      - rule_5.2.19
      - section_5.2
