---

# 5.2.13  Ensure only strong Ciphers are used 

- name: "5.2.13 ->  Ensure only strong Ciphers are used "
  template:
      src: etc/ssh/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
  tags:
      - level1
      - scored
      - control_14.4
      - sshd
      - rule_5.2.13