---

# 5.2.5  Ensure SSH LogLevel is appropiate

- name: "5.2.5 ->  Ensure SSH LogLevel is appropiate"
  template:
      src: etc/ssh/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
  tags:
      - level1
      - scored
      - control_6.2
      - control_6.3
      - sshd
      - rule_5.2.5
      - section_5.2