---

# 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled

- name: "1.1.1.1 -> Ensure mounting of cramfs filesystems is disabled"
  block:
    - name: "1.1.1.1 -> Ensure mounting of cramfs filesystems is disabled (1/2)"
      lineinfile:
        dest: /etc/modprobe.d/CIS.conf
        regexp: "^(#)?install cramfs(\\s|$)"
        line: "install cramfs /bin/true"
        state: present
        owner: root
        group: root
        mode: 0644
        create: true
    - name: "1.1.1.1 -> Ensure mounting of cramfs filesystems is disabled (2/2) | modprobe"
      modprobe:
        name: cramfs
        state: absent
  when: disable_cramfs
  tags:
      - level1
      - scored
      - mount
      - cramfs
      - modprobe
      - filesystems
      - control_5.1
      - rule_1.1.1.1
      - section_1.1
