---

# 1.1.1.6 Ensure mounting of squashfs filesystems is disabled

- name: "1.1.1.6 -> Ensure mounting of squashfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install squashfs(\\s|$)"
      line: "install squashfs /bin/true"
      state: present
      create: true
  tags:
      - level1
      - scored
      - squashfs
      - filesystems
      - control_5.1
      - rule_1.1.1.6
      - section_1.1