---

# 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled

- name: "1.1.1.5 -> Ensure mounting of hfsplus filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install hfsplus(\\s|$)"
      line: "install hfsplus /bin/true"
      state: present
      create: true
  tags:
      - level1
      - scored
      - hfsplus
      - filesystems
      - control_5.1
      - rule_1.1.1.5