---

# 1.1.1.6 Ensure mounting of udf filesystems is disabled (1/2)

- name: "1.1.1.6 -> Ensure mounting of udf filesystems is disabled (1/2)"
  block:
    - name: "1.1.1.6 -> Ensure mounting of udf filesystems is disabled (1/2)"
      lineinfile:
        dest: /etc/modprobe.d/CIS.conf
        regexp: "^(#)?install udf(\\s|$)"
        line: "install udf /bin/true"
        state: present
        create: true
    - name: "1.1.1.6 -> Ensure mounting of udf filesystems is disabled (2/2) | modprobe"
      modprobe:
        name: udf
        state: absent
  when: disable_udf
  tags:
      - level1
      - scored
      - udf
      - modprobe
      - filesystems
      - control_5.1
      - rule_1.1.1.6
      - section_1.1