---

# 1.1.2 -> Ensure /tmp is configured

- name: "1.1.2, 1.1.3, 1.1.4, 1.1.5 -> Ensure /tmp is configured"
  block:
    - name: 1.1.2 Ensure /tmp is configured
      copy:
        src: /usr/share/systemd/tmp.mount
        dest: /etc/systemd/system/tmp.mount
        owner: root
        group: root
        mode: 0644
        force: true
        remote_src: true
    - name: 1.1.2 Ensure /tmp is configured | edit file
      lineinfile:
        dest: /etc/systemd/system/tmp.mount
        regexp: "^Options=mode="
        line: "Options=mode=1777,strictatime,nosuid,nodev,noexec,size={{ temp_dir_size }}"
    - name: 1.1.2 Ensure /tmp is configured | reload demon
      systemd:
        daemon_reload: yes
    - name: 1.1.2 Ensure /tmp is configured | enable and start tmp.mount
      systemd:
        name: tmp.mount
        enabled: yes
        masked: no
        state: started
  tags:
      - level1
      - scored
      - control_5.1
      - rule_1.1.2
      - rule_1.1.3
      - rule_1.1.4
      - rule_1.1.5
      - section_1.1
      - tmp
      - mount