---

# 1.1.11, 1.1.12, 1.1.13, 1.1.14 Ensure separate partition exists for /var/tmp

- name: "1.1.11, 1.1.12, 1.1.13, 1.1.14 -> Ensure separate partition exists for /var/tmp"
  block:
    - name: "1.1.11, 1.1.12, 1.1.13, 1.1.14 -> Ensure separate partition exists for /var/tmp"
      shell: |
        mount | grep "on /var/tmp" && true || true
      register: vartemp
    - name: /var/tmp partitions
      debug:
        msg: "{{ vartemp.stdout_lines }}"
  tags:
      - level2
      - scored
      - control_2.6
      - control_5.1
      - rule_1.1.11
      - rule_1.1.12
      - rule_1.1.13
      - rule_1.1.14
      - section_1.1
      - tmp
      - mount