---

# 1.3.1 Ensure sudo is installed

- name: "1.3.1 -> Ensure sudo is installed"
  apt:
    name: sudo
    state: present
    install_recommends: false
  tags:
      - level1
      - notscored
      - sudo
      - control_5.1
      - rule_1.3.1
      - section_1.3