---

# 1.3.2 Ensure sudo commands use pty

- name: "1.3.2 -> Ensure sudo commands use pty"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^Defaults use_pty"
    line: "Defaults use_pty"
    validate: "visudo -cf %s"
  tags:
      - level1
      - notscored
      - sudo
      - control_5.1
      - rule_1.3.2
      - section_1.3