---

# 1.3.3 Ensure sudo log file exists

- name: "1.3.3 -> Ensure sudo log file exists"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^Defaults logfile.*"
    line: 'Defaults logfile="/var/log/sudo.log"'
    validate: "visudo -cf %s"
  tags:
      - level1
      - notscored
      - sudo
      - control_5.1
      - rule_1.3.3
      - section_1.3