---

# 5.1.6  Ensure permissions on /etc/cron.monthly are configured

- name: "5.1.6 ->  Ensure permissions on /etc/cron.monthly are configured"
  file:
      dest: /etc/cron.monthly
      state: directory
      owner: root
      group: root
      mode: 0700
  tags:
      - level1
      - scored
      - control_14.6
      - cron
      - rule_5.1.6
      - section_5.1