---

# 5.1.7  Ensure permissions on /etc/cron.d are configured

- name: "5.1.7 ->  Ensure permissions on /etc/cron.d are configured"
  file:
      dest: /etc/cron.d
      state: directory
      owner: root
      group: root
      mode: 0700
  tags:
      - level1
      - scored
      - control_14.6
      - cron
      - rule_5.1.7