---

# 3.4.2 Ensure SCTP is disabled

- name: "3.4.2 -> Ensure SCTP is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install sctp(\\s|$)"
      line: "install sctp /bin/true"
      create: true
  tags:
      - level1
      - scored
      - sctp
      - control_9.2
      - rule_3.4.2