---

# 1.8.1.3 Ensure remote login warning banner is configured properly

- name: "1.8.1.3 Ensure remote login warning banner is configured properly"
  template:
      src: etc/issue.net.j2
      dest: /etc/issue.net
  tags:
      - level1
      - notscored
      - banner
      - control_5.1
      - rule_1.8.1.3