---

# 1.8.1.2 Ensure local login warning banner is configured properly

- name: "1.8.1.2 Ensure local login warning banner is configured properly"
  template:
      src: etc/issue.j2
      dest: /etc/issue
  tags:
      - level1
      - notscored
      - banner
      - control_5.1
      - rule_1.8.1.2