---

# 1.8.1.4 Ensure permissions on /etc/motd are configured

- name: "1.8.1.4 -> Ensure permissions on /etc/motd are configured"
  file:
      dest: /etc/motd
      state: file
      owner: root
      group: root
      mode: 0644
  tags:
      - level1
      - notscored
      - perms
      - control_5.1
      - rule_1.8.1.4
      - section_1.8