---

# 1.9 Ensure updates, patches, and additional security software are installed

- name: "1.9 -> Ensure updates, patches, and additional security software are installed"
  apt:
      upgrade: dist
  tags:
      - level1
      - notscored
      - updates
      - control_3.4
      - control_3.5
      - rule_1.8
      - section_1.9