---

# 2.2.11  Ensure email services are not enabled

- name: 2.2.11 -> Check if Service Exists
  stat: 
    path: /etc/init.d/dovecot
  register: service_status
  tags:
      - level1
      - control_9.2
      - email
      - scored
      - rule_2.2.11
      - section_2.2

- name: "2.2.11 -> Ensure email services are not enabled"
  systemd:
    name: dovecot
    enabled: no
  when: service_status.stat.exists
  tags:
      - level1
      - control_9.2
      - email
      - scored
      - rule_2.2.11
      - section_2.2
