---

# 2.2.17  Ensure NIS Server is not enabled

- name: 2.2.17 -> Check if Service Exists
  stat: 
    path: /etc/init.d/nis
  register: service_status

- name: "2.2.17 -> Ensure NIS Server is not enabled"
  systemd:
    name: nis
    enabled: no
  when: service_status.stat.exists
  tags:
      - level1
      - control_9.2
      - nis
      - scored
      - rule_2.2.17
