---

# 2.2.8  Ensure DNS Server is not enabled

- name: 2.2.8 -> Check if Service Exists
  stat: 
    path: /etc/init.d/bind9
  register: service_status
  tags:
      - level1
      - control_9.2
      - dns
      - scored
      - rule_2.2.8
      - section_2.2

- name: "2.2.8 -> Ensure DNS Server is not enabled"
  systemd:
    name: bind9
    enabled: no
  when: service_status.stat.exists
  tags:
      - level1
      - control_9.2
      - dns
      - scored
      - rule_2.2.8
      - section_2.2
