---

# 2.2.12  Ensure Samba is not enabled

- name: 2.2.12 -> Check if Service Exists
  stat: 
    path: /etc/init.d/smbd
  register: service_status
  tags:
      - level1
      - control_9.2
      - samba
      - scored
      - rule_2.2.12
      - section_2.2

- name: "2.2.12 -> Ensure Samba is not enabled"
  systemd:
    name: smbd
    enabled: no
  when: service_status.stat.exists
  tags:
      - level1
      - control_9.2
      - samba
      - scored
      - rule_2.2.12
      - section_2.2
