---

# 3.5.2.3  Ensure loopback traffic is configured

- name: "3.5.2.3 ->  Ensure loopback traffic is configured [1/3]"
  command: ufw allow in on lo
  tags:
      - level1
      - scored
      - firewall
      - control_9.4
      - rule_3.5.2.3
      - section_3.5

- name: "3.5.2.3 ->  Ensure loopback traffic is configured [2/3]"
  command: ufw deny in from 127.0.0.0/8
  tags:
      - level1
      - scored
      - firewall
      - control_9.4
      - rule_3.5.2.3
      - section_3.5

- name: "3.5.2.3 ->  Ensure loopback traffic is configured [3/3]"
  command: ufw deny in from ::1
  tags:
      - level1
      - scored
      - firewall
      - control_9.4
      - rule_3.5.2.3
      - section_3.5