---

# 3.5.1.1  Ensure a Firewall package is installed

- name: "3.5.1.1 ->  Ensure a Firewall package is installed"
  apt:
      name: ufw
      state: present
  tags:
      - level1
      - scored
      - firewall
      - control_9.4
      - rule_3.5.1.1
      - section_3.5