---

# 3.5.2  Ensure default deny firewall policy

- name: "3.5.2 ->  Ensure default deny firewall policy [1/3]"
  command: ufw default deny incoming
  tags:
      - level1
      - scored
      - firewall
      - control_9.4
      - rule_3.5.2
      - section_3.5

- name: "3.5.2 ->  Ensure default deny firewall policy [2/3]"
  command: ufw default deny outgoing
  when: ufw_deny_outgoing
  tags:
      - level1
      - scored
      - firewall
      - control_9.4
      - rule_3.5.2
      - section_3.5

- name: "3.5.2 ->  Ensure default deny firewall policy [3/3]"
  command: ufw default deny routed
  tags:
      - level1
      - scored
      - firewall
      - control_9.4
      - rule_3.5.2
      - section_3.5