---

# 3.5.2.4  Ensure outbound connections are configured

- name: "3.5.2.4 ->  Ensure outbound connections are configured"
  command: ufw allow out on all
  tags:
      - level1
      - scored
      - firewall
      - control_9.4
      - rule_3.5.2.4
      - section_3.5