---

# 5.2.21  Ensure SSH AllowTcpForwarding is disabled

- name: "5.2.21 ->  Ensure SSH AllowTcpForwarding is disabled"
  template:
      src: etc/ssh/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
  tags:
      - level2
      - scored
      - control_9.2
      - sshd
      - rule_5.2.21
      - section_5.2