---

# 3.2.2 Ensure ICMP redirects are not accepted

- name: "3.2.2 -> Ensure ICMP redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
      - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
  notify:
      - sysctl flush ipv4 route table
      - sysctl flush ipv6 route table
  tags:
      - level1
      - scored
      - icmp
      - sysctl
      - control_5.1
      - rule_3.2.2
      - section_3.2