---

# 3.2.9 Ensure IPv6 router advertisements are not accepted

- name: "3.2.9 -> Ensure IPv6 router advertisements are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv6.conf.all.accept_ra, value: 0 }
      - { name: net.ipv6.conf.default.accept_ra, value: 0 }
  notify:
      - sysctl flush ipv6 route table
  tags:
      - level1
      - scored
      - ipv6
      - sysctl
      - control_5.1
      - rule_3.2.9
      - section_3.2