---

# 3.2.8 Ensure TCP SYN Cookies is enabled

- name: "3.2.8 -> Ensure TCP SYN Cookies is enabled"
  sysctl:
      name: net.ipv4.tcp_syncookies
      value: '1'
      state: present
      reload: true
      ignoreerrors: true
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - tcp
      - sysctl
      - control_5.1
      - rule_3.2.8
      - section_3.2