---

# 4.1.17 Ensure the audit configuration is immutable

- name: "4.1.17 -> Ensure the audit configuration is immutable"
  template:
      src: etc/audit/audit.rules.j2
      dest: /etc/audit/rules.d/audit.rules
      owner: root
      group: root
      mode: 0600
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - scored
      - control_6.2
      - control_6.3
      - auditd
      - rule_4.1.17