---

# 4.1.5  Ensure events that modify the system's network environment are collected 

- name: "4.1.5 ->  Ensure events that modify the system's network environment are collected"
  template:
      src: etc/audit/audit.rules.j2
      dest: /etc/audit/rules.d/audit.rules
      owner: root
      group: root
      mode: 0600
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - scored
      - control_5.5
      - auditd
      - rule_4.1.5