---

# 4.1.8 Ensure session initiation information is collected

- name: "4.1.8 -> Ensure session initiation information is collected"
  template:
      src: etc/audit/audit.rules.j2
      dest: /etc/audit/rules.d/audit.rules
      owner: root
      group: root
      mode: 0600
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - scored
      - control_4.9
      - control_16.11
      - control_16.13
      - auditd
      - rule_4.1.8