---

# 4.1.16 Ensure kernel module loading and unloading is collected

- name: "4.1.16 -> Ensure kernel module loading and unloading is collected"
  template:
      src: etc/audit/audit.rules.j2
      dest: /etc/audit/rules.d/audit.rules
      owner: root
      group: root
      mode: 0600
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - scored
      - control_5.1
      - auditd
      - rule_4.1.16
      - section_4.1