---

# 4.1.15 Ensure system administrator actions (sudolog) are collected

- name: "4.1.15 -> Ensure system administrator actions (sudolog) are collected"
  template:
      src: etc/audit/audit.rules.j2
      dest: /etc/audit/rules.d/audit.rules
      owner: root
      group: root
      mode: 0600
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - scored
      - control_4.9
      - auditd
      - rule_4.1.15
      - section_4.1